#!/bin/bash
DIR=/etc/network

howto="Usage: RunwayWifi home/playa"
E_NOARGS=77
E_BADARGS=78

if [ -n "$1" ]
then
  args=$1
  if [ $args == "home" ]
  then
    echo "HOME MODE"
    cp ./RunwayWifiConfigs/interfaces.home $DIR/interfaces
  elif [ $args == "playa" ]
  then
    echo "PLAYA MODE"
    cp ./RunwayWifiConfigs/interfaces.playa $DIR/interfaces
  else
    echo "ERROR! Unknown mode: " $args
    echo $howto
    exit $E_BADARGS
  fi
else
  echo "NOTE: No mode specified. Here's the current interfaces:"
  echo
  more $DIR/interfaces
  echo
  echo "NOTE: If you want to switch modes..."
  echo $howto
  exit $E_NOARGS
fi

more $DIR/interfaces
echo "done"